# Generated by Django 4.1 on 2022-09-09 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='subscribers',
            new_name='subscribe',
        ),
    ]
